package com.johnny.bookstore.model;

public enum CategoryName {
    ACTION_AND_ADVENTURE,
    COMIC,
    CRIME_AND_DETECTIVE,
    FAIRY_TALE,
    HISTORICAL_FICTION,
    HORROR,
    HUMOR,
    ROMANCE,
    SCIENCE_FICTION,
    WEB_GRAPHICS_AND_DESIGN,
    WEB_PROGRAMMING,
    SOFTWARE_ENGINEERING,
    PROGRAMMING_AND_SCRIPTING_LANGUAGE_GENERAL,
    BUSINESS_INNOVATION,
    E_COMMERCE_BUSINESS_ASPECTS,
    ENTREPRENEURSHIP,
    MANAGEMENT_LEADERSHIP_AND_MOTIVATION,
    ORGANIZATIONAL_THEORY_AND_BEHAVIOUR,
    SMALL_BUSINESS_AND_SELF_EMPLOYED,
    INFORMATION_TECHNOLOGY_INDUSTRIES,
    COMPUTER_PROGRAMMING_AND_SOFTWARE_DEVELOPMENT,
    DATABASE_AND_THE_WEB,
    COMPUTER_SCIENCE,
    DATABASES
}