<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <style>
      th {
          text-align: center;
      }
      td {
          word-break: break-word;
      }
  </style>
</head>
<body>
    <h5>Invoice Ref: ${refNo}</h5>
    <h5>Customer: ${name}</h5>
    <h5>Date: ${date}</h5>
    <div>
      <p>Ordered Items: </p>
      <table>
        <thead>
          <tr><th>Title</th><th>Price</th></tr>
        </thead>
        <tbody>
          <#list items as item>
            <tr><td>${item.title}</td><td>${item.price}</td></tr>
          </#list>
        </tbody>
      </table>
    </div>
    <h5>Total: ${amount}</h5>
    <h5>This invoice is generated by ${sender}</h5>
</body>
</html>
